name: mobile
description: "Aplikasi Asisten Digital Petani Indonesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Logic
  supabase_flutter: ^2.3.4
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3
  
  # UI & Navigation
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10
  image_picker: ^1.0.7
  
  # Features
  geolocator: ^11.0.0
  table_calendar: ^3.1.0
  webview_flutter: ^4.7.0
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.2
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.0.1
  connectivity_plus: ^7.0.0
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_final_small.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_final_small.png"
  fullscreen: true
  android: true
  ios: true
  android_gravity: center
  android_12:
    image: "assets/images/logo_final_small.png"
    color: "#ffffff"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
